<?php get_header(); ?><section>	<div id="content" role="main" class="row">		<div class="col-md-12">	<h1 class="large-title center">Каталог товаров по выгодным ценам в Интернет магазинах</h1>	
<div class="row"><?php$settings = array( 'taxonomy' => 'product_cat' );$cats = get_categories( $settings );foreach ($cats as $cat) {		$cat_childrens = get_terms( 'product_cat', array('parent' => $cat->cat_ID, 'hide_empty' => 1  ) );		if($cat_childrens) {			if( get_option('product_cat_'.$cat->cat_ID.'_litle_name_category')) { $cat_litle_name = get_option('product_cat_'.$cat->cat_ID.'_litle_name_category'); } else { $cat_litle_name = $cat->cat_name;}						if(get_option('product_cat_'.$cat->cat_ID.'_number_of_catalog')) { $cat_number = get_option('product_cat_'.$cat->cat_ID.'_number_of_catalog'); } else { $cat_number = '999';}			$term_link = get_term_link((int)$cat->cat_ID, 'product_cat' );				foreach($cat_childrens as $cat_children) {				$cat_children_id = $cat_children->term_id;				$cat_children_link = get_term_link((int)$cat_children_id, 'product_cat' );								if( get_option('product_cat_'.$cat_children_id.'_litle_name_category')) { $cat_children_litle_name = get_option('product_cat_'.$cat_children_id.'_litle_name_category'); } else { $cat_children_litle_name = $cat_children->cat_name;}     								if(get_option('product_cat_'.$cat_children_id.'_number_of_catalog')) { $cat_children_number = get_option('product_cat_'.$cat_children_id.'_number_of_catalog'); } else { $cat_children_number = 999;}								$child_cats[] = array(										'child_name' => $cat_children_litle_name,										'child_link' => $cat_children_link,										'child_number' => $cat_children_number									);			}														$catalog_categoryes[] = array(					'name' => $cat_litle_name,					'link' => $term_link,					'number' => $cat_number,					'child_cats' => $child_cats				);				$child_cats = array();					}			}if($catalog_categoryes) {				function sort_p($c, $d)				{				return strnatcmp($c["number"], $d["number"]);				}				usort($catalog_categoryes, "sort_p");	$cat_list_count = 0;				foreach($catalog_categoryes as $catalog_category) {		$cat_list_count++;		$catalog_list .= '<div class="cat_list col-md-4 block">';		$catalog_list .= '<div class="h5" style="margin-bottom: 10px;">'.$catalog_category['name'].'</div>';		$catalog_list .= "<ul>";								$child_categorys = $catalog_category['child_cats'];			//	function sort_p_child($a, $b) { return strnatcmp($a["child_number"], $b["child_number"]); } usort($child_categorys, "sort_p_child");				//var_dump($child_categorys);				foreach($child_categorys as $child_category) {					$catalog_list .= '<li><a href="'.$child_category['child_link'].'">'.$child_category['child_name'].'</a></li>'; 				}		$catalog_list .= "</ul></div>";		if($cat_list_count == 3) { $catalog_list .= '</div><div class="row">'; $cat_list_count = 0;}	}	echo $catalog_list;}?>	</div><!-- col-md-12 --></div><!-- row --><!--div class="block" -->
<?phpglobal $query_string;  					// добавляем базовые параметры в массив $args  					parse_str($query_string, $args);  					// добавляем/заменяем параметр post_type в массиве  					$args['posts_per_page'] = 32;  					query_posts( $args );

	if ( have_posts() )//	echo '<h2>Все товары в каталоге</h2>';
		the_post();
?>
<?php rewind_posts(); ?><? //get_template_part( 'loop', 'product' ); ?></div>
</section>
<?php get_footer(); ?>